### ISSUE TITLE
Website link is broken

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/orb#16]
The Url on the gap-system.org website for the orb package contains a link to the orb webpage:

http://gap-system.github.io/orb/

This link is currently broken.

**Comment by alex-konovalov** [comment]
@james-d-mitchell thanks - this is a part of a more general issue - see this thread: https://mail.gap-system.org/pipermail/gap/2015-December/000370.html.

Packages overview pages on the GAP website get their information from the PackageInfo.g files of corresponding packages included in the latest stable releasee. For those packages that were moved from gap-system to gap-packages (and orb is one of them) the old URL no longer works. The website links will be fixed automatically after these packages will be updated and included in the next GAP release.

**Comment by james-d-mitchell** [comment]
Thanks @alex-konovalov I must have overlooked that email.

**Comment by james-d-mitchell** [comment]
I'll close this since it is a known issue.
