### ISSUE TITLE
Add functionality to detect if an object has a hash function 

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/orb#17]
Can I propose that we add some functionality to test if there is a `ChooseHashFunction` method for an object? One approach would be simply to return `fail` instead of giving an error as was introduced in change set 5768583. 

In this changeset @fingolin removed the trivial hash function which just returned 1 for every argument, and returned an error instead.

The reason I want this is that in the next major release of the Semigroups package we have some code for enumerating arbitrary finite semigroups, which currently uses the hash tables in Orb. So, in some places we use the trivial hash function, but of course it would be better to have a function that says "there is no hash function for the elements of this semigroups" so that we can use an alternative approach.

**Comment by fingolfin** [comment]
I changed ChooseHashFunction to return `fail`, instead of calling `Error`. Does that help?

**Comment by james-d-mitchell** [comment]
Yup, that will do very nicely. Thanks!
