### ISSUE TITLE
Regression: Make orb usable without compilation

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/orb#25]
Apparently, until recently it was possible to use orb without compiling anything. It run slower, but it run.

This was broken by the addition of `HASH_FUNC_FOR_BLIST`. We should fix that regressions, e.g. by providing a GAP implementation of HASH_FUNC_FOR_BLIST.

**Comment by egri-nagy** [comment]
I used to use a simple but wasteful implementation before: converting the boolean list representation into a list of integers by ```ListBlist``` and call the GAP kernel hash function for lists.

**Comment by egri-nagy** [comment]
correction: I used another Orb hash function.

Actually still patching with that in case the compiled function is not there. See https://github.com/gap-packages/sgpdec/blob/master/patch.g

**Comment by fingolfin** [comment]
Fixed by pr #26
