### ISSUE TITLE
Make IsClosed a property or operation

### ISSUE THREAD

**Issue by markusbaumeister** [gap-packages/orb#34]
Right now, IsClosed is defined as a filter in orbits.gd (line 36). This has the consequence that it can't be defined as a property or operation.

This is bad since it blocks other packages from using this term. For example, IsClosed is used in:
1) the orb-package
2) in the SimplicialSurface-package (to describe closed surfaces)
3) in the ToricVarieties-package (where the same issue was recognized and worked around with, compare ToricSubvarieties.gd)
4) in a possible future package over topology

A classic workaround is using specialized terms like IsClosedSurface, IsClosedSubvariety, IsClosedSet etc. The main disadvantage of this workaround is its user-unfriendliness. It is expected from GAP to be able to call IsClosed - the method selection figures out the rest.

I propose one of the following changes (I slightly prefer the first one)
a) Make IsClosed a property.
    Pro: Very easy to extend, very intuitive
    Con: Possible conflicts if several definitions of IsClosed might apply.
    Con: Bad if someone does not want IsClosed to be an attribute (I don't know of any such cases).
b) Make IsClosed an operation
    Pro: Very flexible and extendible
    Con: Every package has to define a "IsClosedBla"-attribute before defining the operation (which is a bit more work)

**Comment by fingolfin** [comment]
@alex-konovalov I don't think that would be helpful; sure, we can use the *technique* employed there to solve the problem, but there is no need to make changes to the GAP library for this (in fact I think it would be detrimental).

@markusbaumeister Option (a) would be incorrect for `orb`, only option (b) is viable: I'll rename the filter to `IsClosedOrbit`, then declare an operation `IsClosed` with a method for `IsOrbit` inputs that simply maps to `IsClosedOrbit`.

I don't think your "con" for that option is valid, though: It is perfectly legal to declare multiple operations with the same name. You only get a problem if you try to redeclare an option with the same filters:
```
gap> DeclareOperation("foo", [IsGroup]);
gap> DeclareOperation("foo", [IsMatrix]);
gap> DeclareOperation("foo", [IsMatrix]);
#I  equal requirements in multiple declarations for operation `foo'

gap>
```

**Comment by markusbaumeister** [comment]
My "con" did not refer to the operation overloading - that is easy to achieve.
But then it is not possible to make "IsClosed" a property (or an attribute in general). Then one has to declare a property IsClosedBla that is called by the operation IsClosed.
This might be an annoyance one would like to avoid (if possible).

**Comment by fingolfin** [comment]
@markusbaumeister true, but that's the only safe option for overloading names to be used across multiple packages.
