### ISSUE TITLE
Remove use of obsolete SHALLOW_SIZE

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/orb#40]
There are several locations where `SHALLOW_SIZE` is used. It is obsolete and should be replaced by `SIZE_OBJ`, see

https://github.com/gap-system/gap/blob/262e53d0513b507ad187278f28557245e8345cd4/lib/obsolete.gd#L595

**Comment by fingolfin** [comment]
Done in b14a01015cbed465c2220bf387353e0912a2285b
