### ISSUE TITLE
What's the right way to compile orb in 32-bit?

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/orb#45]
Orb is one of the dependencies for Digraphs and Semigroups. We have one Travis job that tests Semigroups against the `stable-4.10` branch of GAP with the newest release of each dependency, with everything (hopefully) compiled for 32-bit. To achieve this, we configure the dependences with
`./configure $PKG_FLAGS`, where
```
PKG_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 LOPTS=-m32 --host=i686-linux-gnu"
```
See, for example, here: https://travis-ci.org/gap-packages/Semigroups/jobs/498376063
Since Orb v4.8.2 was released, with its changed build system, calling `configure` in this way fails (the configure script now expects its first optional argument to be the GAP path).

I know this is not a problem with orb itself, more a problem with how I'm (incorrectly) using it, sorry about that. I basically just want to know what I/we should be doing to compile packages in 32-bit for a 32-bit GAP. Is simply `./configure` now sufficient?

*(Note: I'm not sure why those `PKG_FLAGS` were ever set that way).*

**Comment by fingolfin** [comment]
Sorry, I missed this issue :-(.

You shouldn't have to do anything, actually: as long as you point orb to a 32bit GAP, it should compile a 32bit version of the kernel extension.

**Comment by wilfwilson** [comment]
Thanks @fingolfin. That's what I've been doing, all seems to work 🙂
