### ISSUE TITLE
LoadPackage("orb") failing

### ISSUE THREAD

**Issue by MathieuDutSik** [gap-packages/orb#56]
I used version 4.8.4 and gap-4.11.1
```
gap> LoadPackage("orb");
#I  orb: entering LoadPackage
#I  orb: PackageAvailabilityInfo for version 4.8.4
#I  orb: PackageAvailabilityInfo: the AvailabilityTest function returned 'true'
#I  orb: PackageAvailabilityInfo: no needed packages
#I  orb: PackageAvailabilityInfo: check suggested packages
#I       IO (>= 3.3)
#I  orb: PackageAvailabilityInfo: check of suggested packages done
#I  orb: PackageAvailabilityInfo: version 4.8.4 is available
#I  orb: start loading needed/suggested/self packages
#I       orb
#I  orb: start reading file 'init.g'
Error, variable `Next' is not bound to an operation at /Users/mathieu/opt/gap-4.11.1/lib/oper.g:822 called from
<function "DeclareOperation">( <arguments> )
 called from read-eval loop at /Users/mathieu/opt/gap-4.11.1/pkg/orb-4.8.4/gap/search.gd:35
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk>
```

**Comment by fingolfin** [comment]
Weird! I also just noticed that ghe CI tests failed for 4.8.4. Thank you for the report, I will investigate

**Comment by fingolfin** [comment]
Upon closer inspection, the CI failures are unrelated (the AtlasRep package failed to download some data, hopefully that's a transient condition).

Coming back to your problem: it looks as if something else (loaded before `orb`) has already bound the variable `Next`, either your own code or another (possible unpublished) package.

Is `Next` bound? If so, do you have an idea where it came from? If it is a function, you could use `LocationFunc(Next);` to figure out where it was declared.

**Comment by MathieuDutSik** [comment]
> 

Thank you. I had indeed defined the "Next" in some other package of mine. Sorry for that.
