### ISSUE TITLE
MappingPermListList behaves differently when Orb is compiled than when it is not

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/orb#6]
With Orb uncompiled we get:

```
gap> MappingPermListList([ 1, 1, 2, 3, 3, 2, 2, 1, 2 ], [ 2, 2, 3, 1, 1, 3, 3, 2, 3 ]);
fail
```
and with Orb compiled we get:
```
gap> MappingPermListList([ 1, 1, 2, 3, 3, 2, 2, 1, 2 ], [ 2, 2, 3, 1, 1, 3, 3, 2, 3 ]);
(1,2,3)
```

According to the GAP documentation the first of these is the correct behaviour and the second is incorrect. However, I use the second in several places in the Semigroups package. 

I can work around this for the time being, but probably this should be resolved one way or the other.

**Comment by james-d-mitchell** [comment]
Just to double check, the above was not done, right? If not, then I will do it shortly.

**Comment by fingolfin** [comment]
@james-d-mitchell I think the only thing that happened is that the orb version was renamed to `MappingPermListList_C`.

But anyway, I just had a look through all places in the GAP library we use `MappingPermListList`, and I am by now pretty much convinced that my fear about code relying on it returning `fail` in some situations is unfounded. So perhaps we should go with my original option (1) after all? I.e. move the orb C code to the GAP code; and adapt the documentation? And then I guess the `semigroups` package needs to check upon loading whether to use that, or its custom `MappingPermListList_C` GAP implementation. (i.e. in its read.g, replace
```
if not IsBound(MappingPermListList_C) then
```
by something like
```
if not IsBound(MappingPermListList_C) then
  if MappingPermListList([1,1],[2,2]) <> fail then
    BindGlobal("MappingPermListList_C", MappingPermListList);
  else
    ...
  fi;
fi;
```

**Comment by fingolfin** [comment]
We should settle this during the GAP days next week

**Comment by james-d-mitchell** [comment]
Agreed.

**Comment by fingolfin** [comment]
So we decided to move this to the GAP kernel after all, updating the documentaiton there, and @james-d-mitchell kindly offered to take of this ;-)

**Comment by james-d-mitchell** [comment]
This can be closed, right?

**Comment by fingolfin** [comment]
Yes, thanks.
